[profile.default]
# Number of test retries on failure
retries = 0

# Parallel test threads
test-threads = "num-cpus"

# Timeout for slow tests
slow-timeout = { period = "60s", terminate-after = 3 }

# Output level
status-level = "pass"

# Fail fast on first failure
fail-fast = false

[profile.ci]
# CI profile with 1 retry for flaky tests
retries = 1
fail-fast = false
slow-timeout = { period = "30s", terminate-after = 2 }
